site_name: C++ Primer 章节练习
pages:
  - 主页: index.md
  - 第一章 开始: 
    - 1.1 编写第一个简单的C++程序: C++Primer/Chapter01/Chapter01_01.md
    - 1.2 初识输入输出: C++Primer/Chapter01/Chapter01_02.md
    - 1.3 注释简介: C++Primer/Chapter01/Chapter01_03.md
    - 1.4 流程控制: C++Primer/Chapter01/Chapter01_04.md
    - 1.5 类简介: C++Primer/Chapter01/Chapter01_05.md
    - 1.6 书店程序: C++Primer/Chapter01/Chapter01_06.md
  - 第二章 变量和基本类型: 
    - 2.1 基本内置类型: C++Primer/Chapter02/Chapter02_01.md
    - 2.2 变量: C++Primer/Chapter02/Chapter02_02.md
    - 2.3 复合类型: C++Primer/Chapter02/Chapter02_03.md
    - 2.4 const限定符: C++Primer/Chapter02/Chapter02_04.md
    - 2.5 处理类型: C++Primer/Chapter02/Chapter02_05.md
    - 2.6 自定义数据结构: C++Primer/Chapter02/Chapter02_06.md
  - 第三章 字符串、向量和数组: 
    - 3.1 命名空间的using声明: C++Primer/Chapter03/Chapter03_01.md
    - 3.2 标准库类型string: C++Primer/Chapter03/Chapter03_02.md
    - 3.3 标准库类型vector: C++Primer/Chapter03/Chapter03_03.md
    - 3.4 迭代器介绍: C++Primer/Chapter03/Chapter03_04.md
    - 3.5 数组: C++Primer/Chapter03/Chapter03_05.md
    - 3.6 多维数组: C++Primer/Chapter03/Chapter03_06.md

theme:
  name: 'material'
  logo:
    icon: 'school'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  font:
    text: 'Open Sans'
    code: 'Open Sans Mono'
  language: 'zh'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark

repo_url: https://lablelan.github.io/CppPrimerNote
edit_uri: ""